import os

path = os.path.join(os.path.dirname(__file__), 'src', 'components', 'charts', 'stress-test-chart.tsx')

BT = chr(96)  
DLR = chr(36)

lines = [
    '"use client";',
    '',
    'import {',
    '\tBarChart,',
    '\tBar,',
    '\tYAxis,',
    '\tTooltip,',
    '\tResponsiveContainer,',
    '\tCell,',
    '\tLabelList,',
    '} from "recharts";',
    '',
    'interface StressResult {',
    '\tscenario: string;',
    '\tsimulated_drawdown_pct: number;',
    '\trecovery_days: number | null;',
    '}',
    '',
    'interface StressTestChartProps {',
    '\tdata: StressResult[];',
    '}',
    '',
    '/** Color for bars: ' + chr(45)*2 + 'bg-elevated normally, ' + chr(45)*2 + 'red when drawdown > 15% */',
    'function barFill(drawdown: number): string {',
    '\treturn drawdown > 15 ? "var(' + chr(45)*2 + 'red)" : "var(' + chr(45)*2 + 'bg-elevated)";',
    '}',
    '',
    '/** Custom tooltip styled with ' + chr(45)*2 + 'bg-card, ' + chr(45)*2 + 'border, ' + chr(45)*2 + 'text */',
    'function CustomTooltip({',
    '\tactive,',
    '\tpayload,',
    '}: {',
    '\tactive?: boolean;',
    '\tpayload?: Array<{ payload: StressResult }>;',
    '}) {',
    '\tif (!active || !payload?.length) return null;',
    '\tconst item = payload[0].payload;',
    '',
    '\treturn (',
    '\t\t<div',
    '\t\t\tclassName="rounded border px-3 py-2 text-[12px] font-mono shadow-lg"',
    '\t\t\tstyle={{',
    '\t\t\t\tbackground: "var(' + chr(45)*2 + 'bg-card)",',
    '\t\t\t\tborderColor: "var(' + chr(45)*2 + 'border)",',
    '\t\t\t\tcolor: "var(' + chr(45)*2 + 'text)",',
    '\t\t\t}}',
    '\t\t>',
    '\t\t\t<div className="font-medium mb-1" style={{ color: "var(' + chr(45)*2 + 'text)" }}>',
    '\t\t\t\t{item.scenario}',
    '\t\t\t</div>',
    '\t\t\t<div',
    '\t\t\t\tstyle={{',
    '\t\t\t\t\tcolor:',
    '\t\t\t\t\t\titem.simulated_drawdown_pct > 15 ? "var(' + chr(45)*2 + 'red)" : "var(' + chr(45)*2 + 'text)",',
    '\t\t\t}}',
    '\t\t\t>',
    '\t\t\t\tDrawdown: {item.simulated_drawdown_pct.toFixed(1)}%',
    '\t\t\t</div>',
    '\t\t\t{item.recovery_days != null && (',
    '\t\t\t\t<div style={{ color: "var(' + chr(45)*2 + 'text-muted)" }}>',
    '\t\t\t\t\tRecovery: ~{item.recovery_days}d',
    '\t\t\t\t</div>',
    '\t\t\t)}',
    '\t\t</div>',
    '\t);',
    '}',
    '',
    '/**',
    ' * Horizontal Recharts BarChart consuming RiskOutput.stress_results.',
    ' * Dark theme, ' + chr(45)*2 + 'bg-elevated bars, ' + chr(45)*2 + 'red for drawdown > 15% (V \u00a74.13).',
    ' * X-axis hidden \u2014 value labels on bars replace it.',
    ' */',
    'export function StressTestChart({ data }: StressTestChartProps) {',
    '\tif (!data.length) return null;',
    '',
    '\t// Sort by drawdown descending for visual impact',
    '\tconst sorted = [...data].sort(',
    '\t\t(a, b) => b.simulated_drawdown_pct - a.simulated_drawdown_pct,',
    '\t);',
    '',
    '\treturn (',
    '\t\t<div className="w-full" data-slot="stress-test-chart">',
    '\t\t\t<h3 className="text-[11px] font-mono text-text-muted mb-2 uppercase tracking-wider">',
    '\t\t\t\tStress Test Results',
    '\t\t\t</h3>',
    '\t\t\t<ResponsiveContainer width="100%" height={sorted.length * 40 + 24}>',
    '\t\t\t\t<BarChart',
    '\t\t\t\t\tdata={sorted}',
    '\t\t\t\t\tlayout="vertical"',
    '\t\t\t\t\tmargin={{ top: 8, right: 60, bottom: 8, left: 0 }}',
    '\t\t\t\t>',
    '\t\t\t\t\t<YAxis',
    '\t\t\t\t\t\ttype="category"',
    '\t\t\t\t\t\tdataKey="scenario"',
    '\t\t\t\t\t\ttick={{',
    '\t\t\t\t\t\t\tfill: "var(' + chr(45)*2 + 'text-muted)",',
    '\t\t\t\t\t\t\tfontSize: 11,',
    '\t\t\t\t\t\t\tfontFamily: "var(' + chr(45)*2 + 'font-sans)",',
    '\t\t\t\t\t\t}}',
    '\t\t\t\t\t\taxisLine={false}',
    '\t\t\t\t\t\ttickLine={false}',
    '\t\t\t\t\t\twidth={140}',
    '\t\t\t\t\t/>',
    '\t\t\t\t\t<Tooltip',
    '\t\t\t\t\t\tcontent={<CustomTooltip />}',
    '\t\t\t\t\t\tcursor={{ fill: "var(' + chr(45)*2 + 'bg-elevated)", opacity: 0.3 }}',
    '\t\t\t\t\t/>',
    '\t\t\t\t\t<Bar',
    '\t\t\t\t\t\tdataKey="simulated_drawdown_pct"',
    '\t\t\t\t\t\tradius={[0, 4, 4, 0]}',
    '\t\t\t\t\t\tbarSize={20}',
    '\t\t\t\t\t>',
    '\t\t\t\t\t\t{sorted.map((entry, i) => (',
    '\t\t\t\t\t\t\t<Cell key={i} fill={barFill(entry.simulated_drawdown_pct)} />',
    '\t\t\t\t\t\t))}',
    '\t\t\t\t\t\t<LabelList',
    '\t\t\t\t\t\t\tdataKey="simulated_drawdown_pct"',
    '\t\t\t\t\t\t\tposition="right"',
    '\t\t\t\t\t\t\tformatter={(v: number) => ' + BT + '-' + DLR + '{v.toFixed(1)}%' + BT + '}',
    '\t\t\t\t\t\t\tstyle={{',
    '\t\t\t\t\t\t\t\tfill: "var(' + chr(45)*2 + 'text)",',
    '\t\t\t\t\t\t\t\tfontSize: 11,',
    '\t\t\t\t\t\t\t\tfontFamily: "var(' + chr(45)*2 + 'font-mono)",',
    '\t\t\t\t\t\t\t}}',
    '\t\t\t\t\t\t/>',
    '\t\t\t\t\t</Bar>',
    '\t\t\t\t</BarChart>',
    '\t\t\t</ResponsiveContainer>',
    '\t\t</div>',
    '\t);',
    '}',
]

content = '\n'.join(lines)
with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print('Written successfully')
